/* ═══════════════════════════════════════════════════════
   Editor — MogadocLab
   ═══════════════════════════════════════════════════════ */

// EDITOR
// ═══════════════════════════════════════════════════════════

const EDITOR_DRAFT_KEY='mogadoclab_editor_draft_v2';
const APP_STATE_KEY='mogadoclab_state_v3';
const editorState={history:[],future:[],lastValue:'',dirty:false,lastParsedHash:'',isApplying:false};

function formatXYZFromMol(mol){
  let out=`${mol.atoms.length}\n${mol.name||'Molecule'}\n`;
  mol.atoms.forEach(a=>{out+=`${a.symbol.padEnd(4)} ${a.x.toFixed(6).padStart(12)} ${a.y.toFixed(6).padStart(12)} ${a.z.toFixed(6).padStart(12)}\n`;});
  return out;
}
function formatJSONFromMol(mol){
  return JSON.stringify({
    name: mol.name||'Molecule',
    atoms: mol.atoms.map(a=>({symbol:a.symbol,x:+a.x.toFixed(6),y:+a.y.toFixed(6),z:+a.z.toFixed(6)})),
    bonds: mol.bonds.map(b=>({a:b.a,b:b.b,order:b.order??1,type:b.type||'covalent'}))
  },null,2);
}
function formatMOLFromMol(mol){
  const name=(mol.name||'Molecule').slice(0,80);
  const nA=Math.min(mol.atoms.length,999), nB=Math.min(mol.bonds.length,999);
  let out=`${name}\nMogadocLab\nGenerated by MogadocLab editor\n${String(nA).padStart(3,' ')}${String(nB).padStart(3,' ')}  0  0  0  0            999 V2000\n`;
  mol.atoms.slice(0,999).forEach(a=>{
    out+=`${a.x.toFixed(4).padStart(10)}${a.y.toFixed(4).padStart(10)}${a.z.toFixed(4).padStart(10)} ${a.symbol.padEnd(3)} 0  0  0  0  0  0  0  0  0  0  0  0\n`;
  });
  mol.bonds.slice(0,999).forEach(b=>{
    const order=(b.order===1.5?4:Math.max(1,Math.min(3,Math.round(b.order||1))));
    out+=`${String((b.a||0)+1).padStart(3,' ')}${String((b.b||0)+1).padStart(3,' ')}${String(order).padStart(3,' ')}  0  0  0  0\n`;
  });
  out+='M  END\n';
  return out;
}
function formatPDBFromMol(mol){
  const title=(mol.name||'Molecule').slice(0,60).toUpperCase();
  // PDB convention: HEADER is for classification only. Free-text attribution
  // goes in REMARK 999 (custom-info remark slot). ASCII-only for compatibility
  // with strict PDB parsers.
  let out=`HEADER    EXPORTED BY MOGADOCLAB\nREMARK 999 (c) 2026 K. SARKAR & A. GROSS\nREMARK 999 INSTITUT FUER THEORETISCHE CHEMIE, UNIVERSITAET ULM\nTITLE     ${title}\n`;
  const counters={};
  mol.atoms.forEach((a,i)=>{
    const s=a.symbol;
    counters[s]=(counters[s]||0)+1;
    const serial=String(i+1).padStart(5);
    const label=`${s}${counters[s]}`;
    // 1-char element: leading space + label in cols 14-16. 2-char element: label in cols 13-16.
    const atomName=s.length===1
      ? (' '+label.padEnd(3).slice(0,3))
      : label.padEnd(4).slice(0,4);
    const x=a.x.toFixed(3).padStart(8);
    const y=a.y.toFixed(3).padStart(8);
    const z=a.z.toFixed(3).padStart(8);
    const elem=s.padStart(2);
    out+=`HETATM${serial} ${atomName} UNL A   1    ${x}${y}${z}  1.00  0.00          ${elem}\n`;
  });
  if(mol.bonds && mol.bonds.length){
    const neigh={};
    mol.bonds.forEach(b=>{
      const a=b.a+1, c=b.b+1;
      (neigh[a]=neigh[a]||[]).push(c);
      (neigh[c]=neigh[c]||[]).push(a);
    });
    Object.keys(neigh).map(Number).sort((a,b)=>a-b).forEach(idx=>{
      const list=neigh[idx];
      for(let i=0;i<list.length;i+=4){
        const chunk=list.slice(i,i+4);
        let line=`CONECT${String(idx).padStart(5)}`;
        chunk.forEach(n=>line+=String(n).padStart(5));
        out+=line+'\n';
      }
    });
  }
  out+='END\n';
  return out;
}
function formatGaussianFromMol(mol){
  let out='%nprocshared=4\n%mem=2GB\n%chk=molecule.chk\n# HF/6-31G(d) opt\n\n';
  out+=`${mol.name||'Molecule'} — exported by MogadocLab\n\n`;
  out+='0 1\n';
  mol.atoms.forEach(a=>{
    out+=`${a.symbol.padEnd(3)} ${a.x.toFixed(6).padStart(12)} ${a.y.toFixed(6).padStart(12)} ${a.z.toFixed(6).padStart(12)}\n`;
  });
  out+='\n';
  return out;
}
function formatOrcaFromMol(mol){
  let out='! HF def2-SVP Opt\n\n';
  out+=`# ${mol.name||'Molecule'} — exported by MogadocLab\n\n`;
  out+='* xyz 0 1\n';
  mol.atoms.forEach(a=>{
    out+=`  ${a.symbol.padEnd(3)} ${a.x.toFixed(6).padStart(12)} ${a.y.toFixed(6).padStart(12)} ${a.z.toFixed(6).padStart(12)}\n`;
  });
  out+='*\n';
  return out;
}
function formatVASPFromMol(mol){
  // VASP POSCAR requires atoms grouped by element.
  const grouped={};
  mol.atoms.forEach(a=>{
    (grouped[a.symbol]=grouped[a.symbol]||[]).push(a);
  });
  const symbols=Object.keys(grouped);
  const counts=symbols.map(s=>grouped[s].length);
  // Fabricate a cubic vacuum box around the molecule (no real lattice on import).
  let maxR=0;
  mol.atoms.forEach(a=>{
    const r=Math.max(Math.abs(a.x),Math.abs(a.y),Math.abs(a.z));
    if(r>maxR) maxR=r;
  });
  const box=Math.max(20, Math.ceil((maxR+10)*2));
  let out=`${mol.name||'Molecule'} (exported by MogadocLab)\n`;
  out+='1.0\n';
  out+=`   ${box.toFixed(6).padStart(11)}   0.000000   0.000000\n`;
  out+=`   0.000000   ${box.toFixed(6).padStart(11)}   0.000000\n`;
  out+=`   0.000000   0.000000   ${box.toFixed(6).padStart(11)}\n`;
  out+=`${symbols.join(' ')}\n`;
  out+=`${counts.join(' ')}\n`;
  out+='Cartesian\n';
  symbols.forEach(s=>{
    grouped[s].forEach(a=>{
      out+=`   ${a.x.toFixed(6).padStart(11)}   ${a.y.toFixed(6).padStart(11)}   ${a.z.toFixed(6).padStart(11)}\n`;
    });
  });
  return out;
}
function formatQEFromMol(mol){
  const symbols=[...new Set(mol.atoms.map(a=>a.symbol))];
  const massOf=s=>{
    try{ return (typeof ELEMENTS_DEFAULT!=='undefined' && ELEMENTS_DEFAULT[s]?.mass)||1.0; }
    catch(_){ return 1.0; }
  };
  let out='&CONTROL\n';
  out+=`  calculation = 'scf'\n  prefix = 'mol'\n/\n`;
  out+='&SYSTEM\n';
  out+='  ibrav = 1\n  celldm(1) = 30.0  ! cubic box in a.u., adjust as needed\n';
  out+=`  nat = ${mol.atoms.length}\n  ntyp = ${symbols.length}\n  ecutwfc = 50\n/\n`;
  out+='&ELECTRONS\n/\n';
  out+='ATOMIC_SPECIES\n';
  symbols.forEach(s=>{
    out+=`  ${s.padEnd(3)} ${massOf(s).toFixed(3).padStart(8)}  ${s}.UPF\n`;
  });
  out+='ATOMIC_POSITIONS angstrom\n';
  mol.atoms.forEach(a=>{
    out+=`  ${a.symbol.padEnd(3)} ${a.x.toFixed(6).padStart(12)} ${a.y.toFixed(6).padStart(12)} ${a.z.toFixed(6).padStart(12)}\n`;
  });
  out+='K_POINTS gamma\n';
  return out;
}
function formatCIFFromMol(mol){
  let maxR=0;
  mol.atoms.forEach(a=>{
    const r=Math.max(Math.abs(a.x),Math.abs(a.y),Math.abs(a.z));
    if(r>maxR) maxR=r;
  });
  const cell=Math.max(20, Math.ceil((maxR+10)*2));
  const safe=(mol.name||'Molecule').replace(/[^A-Za-z0-9_-]/g,'_').slice(0,50)||'molecule';
  let out=`data_${safe}\n`;
  out+=`_chemical_name_common              '${(mol.name||'Molecule').replace(/'/g,"\\'")}'\n`;
  out+=`_cell_length_a                     ${cell.toFixed(4)}\n`;
  out+=`_cell_length_b                     ${cell.toFixed(4)}\n`;
  out+=`_cell_length_c                     ${cell.toFixed(4)}\n`;
  out+=`_cell_angle_alpha                  90.0000\n`;
  out+=`_cell_angle_beta                   90.0000\n`;
  out+=`_cell_angle_gamma                  90.0000\n`;
  out+=`_symmetry_space_group_name_H-M     'P 1'\n`;
  out+=`_symmetry_Int_Tables_number        1\n`;
  out+='loop_\n_atom_site_label\n_atom_site_type_symbol\n_atom_site_Cartn_x\n_atom_site_Cartn_y\n_atom_site_Cartn_z\n';
  const counters={};
  mol.atoms.forEach(a=>{
    const s=a.symbol;
    counters[s]=(counters[s]||0)+1;
    const label=`${s}${counters[s]}`;
    out+=`${label.padEnd(6)} ${s.padEnd(3)} ${a.x.toFixed(5).padStart(10)} ${a.y.toFixed(5).padStart(10)} ${a.z.toFixed(5).padStart(10)}\n`;
  });
  return out;
}
function formatMolTo(fmt,mol){
  if(fmt==='xyz')      return formatXYZFromMol(mol);
  if(fmt==='json')     return formatJSONFromMol(mol);
  if(fmt==='mol')      return formatMOLFromMol(mol);
  if(fmt==='pdb')      return formatPDBFromMol(mol);
  if(fmt==='gaussian') return formatGaussianFromMol(mol);
  if(fmt==='orca')     return formatOrcaFromMol(mol);
  if(fmt==='vasp')     return formatVASPFromMol(mol);
  if(fmt==='qe')       return formatQEFromMol(mol);
  if(fmt==='cif')      return formatCIFFromMol(mol);
  return formatXYZFromMol(mol);
}
function getEditorEl(){ return document.getElementById('rawEditor'); }
function getEditorFormat(){ return document.getElementById('editorFormat').value; }
function editorHash(txt){ return `${txt.length}:${txt.slice(0,120)}`; }
function editorSetValue(text,{pushHistory=false,markDirty=true}={}){
  const el=getEditorEl();
  if(pushHistory && !editorState.isApplying && el.value!==text){
    editorState.history.push(el.value);
    if(editorState.history.length>100) editorState.history.shift();
    editorState.future.length=0;
  }
  editorState.isApplying=true;
  el.value=text;
  editorState.isApplying=false;
  editorState.lastValue=text;
  if(markDirty!==null) editorState.dirty=!!markDirty;
  refreshEditorMeta();
  saveEditorDraft();
}
function refreshEditorMeta(extra={}){
  const el=getEditorEl(), val=el.value||'', lines=val?val.split('\n').length:0;
  document.getElementById('editorFmtChip').textContent=getEditorFormat().toUpperCase();
  document.getElementById('editorLineChip').textContent=`${lines} line${lines===1?'':'s'}`;
  document.getElementById('editorCharChip').textContent=`${val.length} chars`;
  const dirty=document.getElementById('editorDirtyChip');
  dirty.textContent=editorState.dirty?'Unsaved':'Clean';
  dirty.className='editor-chip'+(editorState.dirty?' dirty':'');
  if(extra.validity){
    const vc=document.getElementById('editorValidityChip');
    vc.textContent=extra.validity.text;
    vc.className='editor-chip '+extra.validity.cls;
  }
  if(extra.counts){
    document.getElementById('editorAtomChip').textContent=`${extra.counts.atoms} atoms`;
    document.getElementById('editorBondChip').textContent=`${extra.counts.bonds} bonds`;
  }
}
function editorValidate({quiet=false}={}){
  const text=getEditorEl().value.trim(), fmt=getEditorFormat();
  if(!text){
    refreshEditorMeta({validity:{text:'Empty',cls:'bad'},counts:{atoms:0,bonds:0}});
    if(!quiet) notify('Editor is empty','error');
    return null;
  }
  try{
    const mol=parseMolecule('editor.'+fmt,text);
    refreshEditorMeta({validity:{text:'Valid',cls:'good'},counts:{atoms:mol.atoms.length,bonds:mol.bonds.length}});
    if(!quiet) notify(`Validated ${mol.atoms.length} atoms and ${mol.bonds.length} bonds`,'success');
    return mol;
  }catch(e){
    refreshEditorMeta({validity:{text:'Invalid',cls:'bad'},counts:{atoms:0,bonds:0}});
    if(!quiet) notify('Validation failed: '+e.message,'error');
    return null;
  }
}
function parseFromEditor(){
  const mol=editorValidate({quiet:true});
  if(!mol) return notify('Parse error: invalid editor content','error');
  loadMolecule('From editor',mol);
  editorState.dirty=false;
  editorState.lastParsedHash=editorHash(getEditorEl().value);
  refreshEditorMeta({validity:{text:'Rendered',cls:'good'},counts:{atoms:mol.atoms.length,bonds:mol.bonds.length}});
  saveEditorDraft();
  notify(`Rendered ${mol.atoms.length} atoms from ${getEditorFormat().toUpperCase()} editor`,'success');
}
function loadEditorFromMolecule(){
  if(!molecule)return notify('No structure loaded','error');
  const fmt=getEditorFormat();
  editorSetValue(formatMolTo(fmt,molecule),{pushHistory:true,markDirty:false});
  editorState.lastParsedHash=editorHash(getEditorEl().value);
  editorValidate({quiet:true});
  notify(`Loaded current molecule into ${fmt.toUpperCase()} editor`,'success');
}
function editorUndo(){
  if(!editorState.history.length) return notify('Nothing to undo','error');
  const el=getEditorEl();
  editorState.future.push(el.value);
  const prev=editorState.history.pop();
  editorSetValue(prev,{pushHistory:false,markDirty:true});
}
function editorRedo(){
  if(!editorState.future.length) return notify('Nothing to redo','error');
  const el=getEditorEl();
  editorState.history.push(el.value);
  const next=editorState.future.pop();
  editorSetValue(next,{pushHistory:false,markDirty:true});
}
function editorPrettify(){
  const mol=editorValidate({quiet:true});
  if(!mol) return notify('Cannot prettify invalid content','error');
  const pretty=formatMolTo(getEditorFormat(),{...mol,name:molecule?.name||'Molecule'});
  editorSetValue(pretty,{pushHistory:true,markDirty:true});
  editorValidate({quiet:true});
  notify('Editor content normalized','success');
}
function editorConvertFormat(){
  const mol=editorValidate({quiet:true}) || molecule;
  if(!mol) return notify('Nothing valid to convert','error');
  const fmt=getEditorFormat();
  editorSetValue(formatMolTo(fmt,{...mol,name:mol.name||molecule?.name||'Molecule'}),{pushHistory:true,markDirty:true});
  editorValidate({quiet:true});
  notify(`Converted editor to ${fmt.toUpperCase()}`,'success');
}
function editorCopy(){
  const val=getEditorEl().value;
  if(!val.trim()) return notify('Editor is empty','error');
  navigator.clipboard.writeText(val).then(()=>notify('Editor text copied','success')).catch(()=>notify('Clipboard copy failed','error'));
}
function editorDownload(){
  const val=getEditorEl().value;
  if(!val.trim()) return notify('Editor is empty','error');
  const fmt=getEditorFormat(), mime=fmt==='json'?'application/json':'text/plain';
  download(val,`${(molecule?.name||'molecule_editor').replace(/\s+/g,'_')}.${fmt}`,mime);
  notify(`Saved ${fmt.toUpperCase()} editor text`,'success');
}
function saveEditorDraft(){
  try{
    const payload={text:getEditorEl().value,format:getEditorFormat(),dirty:editorState.dirty,lastParsedHash:editorState.lastParsedHash};
    localStorage.setItem(EDITOR_DRAFT_KEY,JSON.stringify(payload));
  }catch(_){}
}
function restoreEditorDraft(){
  try{
    const raw=localStorage.getItem(EDITOR_DRAFT_KEY);
    if(!raw) return false;
    const draft=JSON.parse(raw);
    if(draft.format) document.getElementById('editorFormat').value=draft.format;
    if(typeof draft.text==='string' && draft.text.trim()){
      editorSetValue(draft.text,{pushHistory:false,markDirty:!!draft.dirty});
      editorState.lastParsedHash=draft.lastParsedHash||'';
      editorValidate({quiet:true});
      return true;
    }
  }catch(_){}
  return false;
}
function saveAppState(){
  try{
    const state={
      savedViewportWidth: window.innerWidth || 0,
      theme: document.documentElement.getAttribute('data-theme')||'dark',
      viewMode, lightingMode, colorScheme, rotMode, rotEasing,
      rotTilt: Math.round((rotTiltAngle||0)*180/Math.PI),
      autoRotate, showLabels, showInfo,
      bg: document.getElementById('canvasArea').getAttribute('data-bg')||'grid',
      atomScale: document.getElementById('atomScale').value,
      bondWidth: document.getElementById('bondWidth').value,
      depthFog: document.getElementById('depthFog').value,
      glowAmt: document.getElementById('glowAmt').value,
      rotSpeed: document.getElementById('rotSpeed').value,
      molecule: molecule?{
        name:molecule.name||'Molecule',
        atoms:molecule.atoms.map(a=>({symbol:a.symbol,x:a.x,y:a.y,z:a.z,idx:a.idx})),
        bonds:molecule.bonds.map(b=>({a:b.a,b:b.b,order:b.order,type:b.type}))
      }:null
    };
    localStorage.setItem(APP_STATE_KEY,JSON.stringify(state));
  }catch(_){}
}
function restoreAppState(){
  try{
    const raw=localStorage.getItem(APP_STATE_KEY);
    if(!raw) return false;
    const s=JSON.parse(raw);
    const isCompactViewport = window.matchMedia('(max-width: 768px)').matches;
    const wasSavedFromCompactViewport = Number(s.savedViewportWidth||0) > 0 && Number(s.savedViewportWidth) <= 768;
    if(s.theme) setTheme(s.theme==='dark'?'dark':s.theme);
    if(s.bg) setBg(s.bg);
    if(s.viewMode) setViewMode(s.viewMode);
    if(s.lightingMode) setLighting(s.lightingMode);
    if(s.colorScheme) setColorScheme(s.colorScheme);
    if(s.rotMode) setRotMode(s.rotMode);
    if(typeof s.rotEasing==='boolean') setRotEasing(s.rotEasing);
    if(typeof s.rotTilt==='number') { document.getElementById('rotTilt').value=s.rotTilt; setRotTilt(s.rotTilt); }
    [['atomScale',s.atomScale],['bondWidth',s.bondWidth],['depthFog',s.depthFog],['glowAmt',s.glowAmt],['rotSpeed',s.rotSpeed]].forEach(([id,v])=>{ if(v!=null) document.getElementById(id).value=v; });
    updateDisplay();
    const sidebar=document.getElementById('sidebar');
    sidebar.classList.remove('collapsed','expanded','super-expanded');
    document.getElementById('searchSection')?.classList.remove('search-expanded');
    if(isCompactViewport){
      sidebar.classList.remove('expanded','super-expanded');
      sidebar.classList.add('collapsed');
      document.getElementById('searchSection')?.classList.remove('search-expanded');
    } else if(wasSavedFromCompactViewport){
      sidebar.classList.remove('collapsed');
      document.getElementById('searchSection')?.classList.remove('search-expanded');
    }
    normalizeSidebarState?.({forceDesktopVisible:true});
    const dbExpandBtn=document.getElementById('dbExpandBtn');
    if(dbExpandBtn){
      if(document.getElementById('searchSection')?.classList.contains('search-expanded')) dbExpandBtn.textContent='⤡ Compact';
      else dbExpandBtn.textContent='⤢ Expand';
    }
    document.getElementById('sidebarToggle').textContent=document.getElementById('sidebar').classList.contains('collapsed')?'›':'‹';
    document.getElementById('editorPanel').classList.add('hidden');
    updateSidebarToggleUI();
    if(s.molecule?.atoms?.length) loadMolecule(s.molecule.name||'Recovered Molecule',{atoms:s.molecule.atoms,bonds:s.molecule.bonds||[]});
    if(s.autoRotate && !autoRotate) toggleAutoRotate();
    if(s.showLabels && !showLabels) toggleLabels();
    if(s.showInfo && !showInfo) toggleInfo();
    return true;
  }catch(_){
    return false;
  }
}
try{
  localStorage.removeItem('mogadoclab_state_v2');
}catch(_){}
function initEditorRegime(){
  const ed=getEditorEl(), fmt=document.getElementById('editorFormat');
  ed.addEventListener('input',()=>{
    if(editorState.isApplying) return;
    if(ed.value!==editorState.lastValue){
      editorState.history.push(editorState.lastValue);
      if(editorState.history.length>100) editorState.history.shift();
      editorState.future.length=0;
      editorState.lastValue=ed.value;
    }
    editorState.dirty=editorHash(ed.value)!==editorState.lastParsedHash;
    refreshEditorMeta();
    saveEditorDraft();
  });
  ed.addEventListener('keydown',e=>{
    if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){ parseFromEditor(); e.preventDefault(); }
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){ editorDownload(); e.preventDefault(); }
    if((e.ctrlKey||e.metaKey)&&!e.shiftKey&&e.key.toLowerCase()==='z'){ editorUndo(); e.preventDefault(); }
    if(((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y')||((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='z')){ editorRedo(); e.preventDefault(); }
  });
  fmt.addEventListener('change',()=>{
    refreshEditorMeta();
    if(ed.value.trim()) editorConvertFormat();
    saveEditorDraft();
  });
  restoreEditorDraft();
  if(!ed.value.trim() && molecule) loadEditorFromMolecule();
  else refreshEditorMeta();
  window.addEventListener('beforeunload',()=>{ saveEditorDraft(); saveAppState(); });
}
// ─── DRAG & DROP ──────────────────────────────────────────
const fileDrop=document.getElementById('fileDrop');
fileDrop.addEventListener('dragover',e=>{e.preventDefault();fileDrop.classList.add('drag-over');});
fileDrop.addEventListener('dragleave',()=>fileDrop.classList.remove('drag-over'));
function handleDroppedFile(file){
  if(!file) return;
  const reader=new FileReader();
  reader.onload=ev=>{
    try{
      loadStructureText(file.name, ev.target.result, { displayName: file.name.replace(/\.[^.]+$/,'') });
    }catch(err){notify('Import failed: '+err.message,'error');}
  };
  reader.readAsText(file);
}
fileDrop.addEventListener('drop',e=>{e.preventDefault();fileDrop.classList.remove('drag-over');handleDroppedFile(e.dataTransfer.files[0]);});
const canvasArea=document.getElementById('canvasArea');
canvasArea.addEventListener('dragover',e=>e.preventDefault());
canvasArea.addEventListener('drop',e=>{e.preventDefault();handleDroppedFile(e.dataTransfer.files[0]);});

// ─── NOTIFICATIONS ─────────────────────────────────────────
let notifTimer=null;
function notify(msg,type='success'){
  const el=document.getElementById('notification'),icons={success:'✓',error:'✕',info:'ℹ'};
  document.getElementById('notifIcon').textContent=icons[type]||'';
  document.getElementById('notifMsg').textContent=msg;
  el.className='show '+type;
  if(notifTimer)clearTimeout(notifTimer);
  notifTimer=setTimeout(()=>el.className='',3500);
}
function clearMolecule(){
  if(typeof clearTrajectory==='function' && trajectoryFrames?.length){
    clearTrajectory();
  }
  molecule=null;
  document.getElementById('emptyState').style.display='flex';
  const mb=document.getElementById('moleculeName');mb.textContent='No structure loaded';mb.classList.remove('loaded');
  document.getElementById('headerFormula').textContent='';document.getElementById('headerFormula').classList.remove('visible');
  ['statAtoms','statBonds','statElems'].forEach(id=>document.getElementById(id).textContent='0');
  ['statMW','statFormula'].forEach(id=>document.getElementById(id).textContent='—');
  document.getElementById('atomLegend').innerHTML='<div style="font-family:\'JetBrains Mono\',monospace;font-size:10px;color:var(--text-muted);">Load a molecule to see elements</div>';
  render();
  saveAppState();
}

// ═══════════════════════════════════════════════════════════
